### PR TITLE
update api

### PR DESCRIPTION
**Pull request by lunika**

### CODE REVIEW

**Comment by roadster31** [comment]
Files changed: 21,472

Wow.

**Comment by lunika** [comment]
It's just the API documentation :-)

**Comment by roadster31** [comment]
You mean the *source code* of the documentation ?

**Comment by lunika** [comment]
yes

**Comment by lunika** [comment]
No, the documentation of the source code

**Comment by lunika** [comment]
> Win, the “yes” needs the “no” to win, against the “no”

**Comment by roadster31** [comment]
As far as I can read plain English, this is not a documentation, just a bunch of YAML ;)

**Pull request merged**
