### PR TITLE
Added missing arguments and results in lang loop

### PR DESCRIPTION
**Pull request by roadster31**

### CODE REVIEW

**Comment by lunika** [comment]
can you specify the from_version parameter. It was introduced in PR #150. With it you know if you can use a paramer in your version or not.

Thanks.

**Comment by roadster31** [comment]
Sure. The next version will be 2.2.beta2 ?

**Comment by lunika** [comment]
yes but you can put only ```2.2```

**Comment by bibich** [comment]
Thanks

**Pull request merged**
