### PR TITLE
Added missing commas

### PR DESCRIPTION
**Pull request by roadster31**
... for brand and folder loop. What about a good old Wiki instead of this hand-coded (yeah, this IS code), hard to maintain stuff ?

- Most Thelia users have no idea about the way to contributing to the doc.
- There's no documentation of the documentation syntax.
- The loop documentation text is very poor (e.g, "Currency loop lists currencies." Ha ha.), and lacks use cases, mostly because writing the loop documentation is a real pain in the ass !
- etc.

Hint: MediaWiki supports Markdown :)

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Thanks !

We noted your observation.

**Comment by gillesbourgeat** [comment]
The unit tests does not work :(
https://travis-ci.org/thelia/thelia.github.io/builds/89311473

**Comment by roadster31** [comment]
@gillesbourgeat this is the build for #178, not #180.

**Comment by gillesbourgeat** [comment]
I know, i make a remark for the PR 178 :)

**Pull request merged**
